require("pry")
require_relative("../models/album")
require_relative("../models/artist")

Album.delete_all()
Artist.delete_all()


artist1 = Artist.new({'name' => 'Travis'})
artist2 = Artist.new({'name' => 'Queen'})
artist1.save()
artist2.save()

album01 = Album.new({'title' => 'Good Feeling', 'genre' => 'Britpop', 'released' => 1997, 'artist_id' => artist1.id})
album02 = Album.new({'title' => 'The Man Who', 'genre' => 'Britpop', 'released' => 1999, 'artist_id' => artist1.id})
album03 = Album.new({'title' => 'The Invisible Band', 'genre' => 'Britpop', 'released' => 2001, 'artist_id' => artist1.id})
album04 = Album.new({'title' => '12 Memories', 'genre' => 'Britpop', 'released' => 2003, 'artist_id' => artist1.id})
album05 = Album.new({'title' => 'The Boy with No Name', 'genre' => 'Britpop', 'released' => 2007, 'artist_id' => artist1.id})
album06 = Album.new({'title' => 'Ode to J.Smith', 'genre' => 'Britpop', 'released' => 2008, 'artist_id' => artist1.id})
album07 = Album.new({'title' => 'Where You Stand', 'genre' => 'Britpop', 'released' => 2013, 'artist_id' => artist1.id})
album08 = Album.new({'title' => 'Everything at Once', 'genre' => 'Britpop', 'released' => 2016, 'artist_id' => artist1.id})
album09 = Album.new({'title' => 'Queen', 'genre' => 'Rock', 'released' => 1973, 'artist_id' => artist2.id})
album10 = Album.new({'title' => 'Queen II', 'genre' => 'Rock', 'released' => 1974, 'artist_id' => artist2.id})
album11 = Album.new({'title' => 'Sheer Heart Attack', 'genre' => 'Rock', 'released' => 1974, 'artist_id' => artist2.id})
album12 = Album.new({'title' => 'A Night at the Opera', 'genre' => 'Rock', 'released' => 1975, 'artist_id' => artist2.id})
album13 = Album.new({'title' => 'A Day at the Races', 'genre' => 'Rock', 'released' => 1976, 'artist_id' => artist2.id})
album14 = Album.new({'title' => 'News of the World', 'genre' => 'Rock', 'released' => 1977, 'artist_id' => artist2.id})
album15 = Album.new({'title' => 'Jazz', 'genre' => 'Rock', 'released' => 1978, 'artist_id' => artist2.id})
album16 = Album.new({'title' => 'The Game', 'genre' => 'Rock', 'released' => 1980, 'artist_id' => artist2.id})
album17 = Album.new({'title' => 'Flash Gordon', 'genre' => 'Rock', 'released' => 1980, 'artist_id' => artist2.id})
album18 = Album.new({'title' => 'Hot Space', 'genre' => 'Rock', 'released' => 1982, 'artist_id' => artist2.id})
album19 = Album.new({'title' => 'The Works', 'genre' => 'Rock', 'released' => 1984, 'artist_id' => artist2.id})
album20 = Album.new({'title' => 'A Kind of Magic', 'genre' => 'Rock', 'released' => 1986, 'artist_id' => artist2.id})
album21 = Album.new({'title' => 'The Miracle', 'genre' => 'Rock', 'released' => 1989, 'artist_id' => artist2.id})
album22 = Album.new({'title' => 'Innuendo', 'genre' => 'Rock', 'released' => 1991, 'artist_id' => artist2.id})
album23 = Album.new({'title' => 'Made in Heaven', 'genre' => 'Rock', 'released' => 1995, 'artist_id' => artist2.id})
album01.save()
album02.save()
album03.save()
album04.save()
album05.save()
album06.save()
album07.save()
album08.save()
album09.save()
album10.save()
album11.save()
album12.save()
album13.save()
album14.save()
album15.save()
album16.save()
album17.save()
album18.save()
album19.save()
album20.save()
album21.save()
album22.save()
album23.save()


artist1.album()
artist2.album()

album01.artist()
album23.artist()


binding.pry
nil
